=== Carlosdi1106/visualizadorCurricula/visualizadorCurricula/input/erasmus.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:era="http://www.erasmus.org"
    elementFormDefault="qualified" targetNamespace="http://www.erasmus.org"
    xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">

    <xs:element name="Erasmus">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Estudiante" type="era:estudianteT"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="estudianteT">
        <xs:sequence>
            <xs:element type="era:nombreT" name="NombreCompleto"/>
            <xs:element type="xs:date" name="FechaNacimiento"/>
            <xs:element type="era:universidadT" name="Universidad"/>
            <xs:element type="era:datosContactoT" name="DatosContacto"/>
            <xs:element type="era:cartaT" name="CartaPresentacion"/>
            <xs:element type="era:nivelIdiomasT" name="NivelIdiomas"/>
            <xs:element type="era:todasAsignaturasT" name="Asignaturas"/>
            <xs:element type="era:cuatrimestreT" name="CuatrimestreDeEstancia"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="NumeroIdentificacion" use="required"/>
        <!-- Assert que asegura que el estudiante sea mayor de edad -->

        <!-- Assert que comprueba que la suma de creditos sea la correcta:
            Si el alumno solo esta un cuatrimestre sus creditos deben sumar 30 exactamente
            En cambio si va el año entero la suma de creditos deber estar entre 48 y 60-->
        <xs:assert  test="
                if (.//era:CuatrimestreDeEstancia[text() = 'Anual']) then
                    sum(.//era:Asignatura/era:Creditos) &lt; 61 and
                    sum(.//era:Asignatura/era:Creditos) &gt; 47
                else
                    sum(.//era:Asignatura/era:Creditos) = 30"> </xs:assert >

        <!-- Assert que comprueba que las asignaturas se imparten en mismo cuatrimestre que va el alumno
        en caso de que vaya el año entero no lo comprueba-->
        <xs:assert test="
                every $cuatriAsignatura in (.//era:Asignaturas/era:Asignatura/era:Cuatrimestre)
                    satisfies if (.//era:CuatrimestreDeEstancia[text() = 'Anual'])
                    then
                        1=1
                    else
                        $cuatriAsignatura = .//era:CuatrimestreDeEstancia"/>

    </xs:complexType>


    <xs:complexType name="nombreT">
        <xs:sequence>
            <xs:element type="xs:string" name="Nombre"/>
            <xs:element type="xs:string" name="PrimerApellido"/>
            <xs:element type="xs:string" name="SegundoApellido" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="universidadT">
        <xs:sequence>
            <xs:element type="xs:string" name="NombreUni"/>
            <xs:element type="era:procedenciaT" name="Procedencia"/>
            <xs:element type="era:gradoT" name="Grados"/>
            <xs:any namespace="any" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="procedenciaT">
        <xs:sequence>
            <xs:element type="xs:string" name="Pais"/>
            <xs:element type="xs:int" name="CodigoPostal"/>
            <xs:element type="xs:string" name="Ciudad"/>
            <xs:any namespace="any" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="gradoT">
        <xs:sequence>
            <xs:choice minOccurs="1">
                <xs:element type="xs:string" name="Grado"/>
                <xs:element type="xs:string" name="Master"/>
                <xs:element type="xs:string" name="Doctorado"/>
            </xs:choice>
            <xs:element type="xs:string" name="Facultad"/>
            <xs:element type="xs:string" name="Campus"/>
            <xs:any namespace="any" minOccurs="0"/>
        </xs:sequence>

        <xs:attribute type="xs:int" name="Curso" use="required"/>
    </xs:complexType>

    <xs:complexType name="datosContactoT">
        <xs:sequence>
            <xs:element type="xs:string" name="PrefijoTelefono"/>
            <xs:element type="xs:string" name="Telefono"/>
            <xs:element type="xs:string" name="CorreoElectronico"/>
            <xs:element type="era:direccionT" name="Direccion"/>
            <xs:any namespace="any" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="direccionT">
        <xs:complexContent>
            <xs:extension base="era:procedenciaT">
                <xs:sequence>
                    <xs:element type="xs:string" name="NombreCalle"/>
                    <xs:element type="xs:int" name="NumeroPortal"/>
                    <xs:element type="xs:string" name="Piso"/>
                    <xs:element type="xs:string" name="Puerta"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType mixed="true" name="cartaT">
        <xs:sequence>
            <xs:element type="xs:string" name="UniversidadDestino"/>
            <xs:element type="xs:string" name="PaisDestino"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="nivelIdiomasT">
        <xs:sequence>
            <xs:element type="era:nivelIdiomaT" name="Certificado" minOccurs="0"
                maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="nivelIdiomaT">
        <xs:simpleContent>
            <xs:extension base="era:nivelCertificadoT">
                <xs:attribute type="xs:string" name="Idioma" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:simpleType name="nivelCertificadoT">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-C]{1}[1-2]{1}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="todasAsignaturasT">
        <xs:sequence>
            <xs:element name="Asignatura" type="era:asignaturaT" maxOccurs="15"/>
        </xs:sequence>

        <!--Assert que comprueba que los nombres de las asignaturas no se repiten,
            para evitar que se haya apuntado dos veces a la misma asignatura-->
        <xs:assert
            test="count(.//era:Asignatura/@NombreAsignatura) = count(distinct-values(.//era:Asignatura/@NombreAsignatura))"
        />
    </xs:complexType>

    <xs:complexType name="asignaturaT">
        <xs:sequence>
            <xs:element name="Cuatrimestre" type="era:cuatrimestreT"/>
            <xs:element name="Creditos" type="era:creditosT"/>
        </xs:sequence>
        <xs:attribute name="NombreAsignatura" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:simpleType name="creditosT">
        <xs:restriction base="xs:float">
            <xs:minExclusive value="3"/>
            <xs:maxInclusive value="12"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="cuatrimestreT">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Primero"/>
            <xs:enumeration value="Segundo"/>
            <xs:enumeration value="Anual"/>
        </xs:restriction>
    </xs:simpleType>



</xs:schema>

=== Carlosdi1106/visualizadorCurricula/visualizadorCurricula/input/lukasKrause.xml
<?xml version="1.0" encoding="UTF-8"?>
<Erasmus xmlns="http://www.erasmus.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:al="http://www.erasmus-alemania.org"
    xsi:schemaLocation="http://www.erasmus.org erasmus.xsd http://www.erasmus-alemania.org alemania.xsd">

    <Estudiante NumeroIdentificacion="12345" xsi:type="al:estudianteAlemanT">
        <NombreCompleto>
            <Nombre>Lukas</Nombre>
            <PrimerApellido>Krause</PrimerApellido>
        </NombreCompleto>
        <FechaNacimiento>2001-06-11</FechaNacimiento>
        <Universidad>
            <NombreUni>Universidad Técnica de Múnich</NombreUni>
            <Procedencia>
                <Pais>Alemania</Pais>
                <CodigoPostal>20000</CodigoPostal>
                <Ciudad>Munich</Ciudad>
            </Procedencia>
            <Grados Curso="3" xsi:type="al:gradoAlemaniaT">
                <Grado>Ingenieria Informatica</Grado>
                <Facultad>Facultad de Informatica</Facultad>
                <Campus>Biergartem Campus</Campus>
                <al:NotaMediaGrado>4.4</al:NotaMediaGrado>
                <al:Asignaturas>
                    <al:Asignatura>
                        <al:Nombre>Fundamentos de la informática</al:Nombre>
                        <al:NotaMedia>4.0</al:NotaMedia>
                    </al:Asignatura>
                    <al:Asignatura>
                        <al:Nombre>Programación I y II</al:Nombre>
                        <al:NotaMedia>5.0</al:NotaMedia>
                    </al:Asignatura>
                    <al:Asignatura>
                        <al:Nombre>Estructuras de datos y algoritmos</al:Nombre>
                        <al:NotaMedia>5.6</al:NotaMedia>
                    </al:Asignatura>
                    <al:Asignatura>
                        <al:Nombre>Fundamentos de la ingeniería de software</al:Nombre>
                        <al:NotaMedia>6.0</al:NotaMedia>
                    </al:Asignatura>
                    <al:Asignatura>
                        <al:Nombre>Sistemas operativos</al:Nombre>
                        <al:NotaMedia>3.4</al:NotaMedia>
                    </al:Asignatura>
                    <al:Asignatura>
                        <al:Nombre>Bases de datos</al:Nombre>
                        <al:NotaMedia>3.0</al:NotaMedia>
                    </al:Asignatura>
                    <al:Asignatura>
                        <al:Nombre>Redes de computadoras</al:Nombre>
                        <al:NotaMedia>4.5</al:NotaMedia>
                    </al:Asignatura>
                    <al:Asignatura>
                        <al:Nombre>Arquitectura de computadoras</al:Nombre>
                        <al:NotaMedia>4.8</al:NotaMedia>
                    </al:Asignatura>
                    <al:Asignatura>
                        <al:Nombre>Matemáticas para informática</al:Nombre>
                        <al:NotaMedia>4.2</al:NotaMedia>
                    </al:Asignatura>
                    <al:Asignatura>
                        <al:Nombre>Sistemas operativos</al:Nombre>
                        <al:NotaMedia>4.3</al:NotaMedia>
                    </al:Asignatura>
                </al:Asignaturas>
            </Grados>
        </Universidad>
        <DatosContacto>
            <PrefijoTelefono>49</PrefijoTelefono>
            <Telefono>987654321</Telefono>
            <CorreoElectronico>correoaleman@alemania.aleman</CorreoElectronico>
            <Direccion>
                <Pais>Alemania</Pais>
                <CodigoPostal>20001</CodigoPostal>
                <Ciudad>Munich</Ciudad>
                <NombreCalle>Biergarten am Chinesischer Turm</NombreCalle>
                <NumeroPortal>2</NumeroPortal>
                <Piso>3</Piso>
                <Puerta>A</Puerta>
            </Direccion>
        </DatosContacto>
        <CartaPresentacion>
            <UniversidadDestino>Universidad del País Vasco</UniversidadDestino>
            <PaisDestino>España</PaisDestino>
        </CartaPresentacion>
        <NivelIdiomas>
            <Certificado Idioma="Castellano">B2</Certificado>
            <Certificado Idioma="Ingles">B2</Certificado>
        </NivelIdiomas>
        <Asignaturas>
            <Asignatura NombreAsignatura="Diseño de Videojuegos I">
                <Cuatrimestre>Primero</Cuatrimestre>
                <Creditos>6</Creditos>
            </Asignatura>
            <Asignatura NombreAsignatura="Calidad de Software">
                <Cuatrimestre>Primero</Cuatrimestre>
                <Creditos>6</Creditos>
            </Asignatura>
            <Asignatura NombreAsignatura="Desarrollo Industrial de Software">
                <Cuatrimestre>Primero</Cuatrimestre>
                <Creditos>6</Creditos>
            </Asignatura>
            <Asignatura NombreAsignatura="Diseño de Base de Datos">
                <Cuatrimestre>Primero</Cuatrimestre>
                <Creditos>6</Creditos>
            </Asignatura>
            <Asignatura NombreAsignatura="Diseño de Videojuegos II">
                <Cuatrimestre>Segundo</Cuatrimestre>
                <Creditos>6</Creditos>
            </Asignatura>
            <Asignatura NombreAsignatura="Gestion Avanzada de Informacion">
                <Cuatrimestre>Segundo</Cuatrimestre>
                <Creditos>6</Creditos>
            </Asignatura>
            <Asignatura NombreAsignatura="Sistemas Web">
                <Cuatrimestre>Segundo</Cuatrimestre>
                <Creditos>6</Creditos>
            </Asignatura>
            <Asignatura NombreAsignatura="Gestion de Proyectos">
                <Cuatrimestre>Segundo</Cuatrimestre>
                <Creditos>6</Creditos>
            </Asignatura>
        </Asignaturas>
        <CuatrimestreDeEstancia>Anual</CuatrimestreDeEstancia>
        <al:ExperienciasProfesionales>
            <al:ExperienciaProfesional>
                <al:NombreEmpresa>Audi</al:NombreEmpresa>
                <al:Puesto>Programador Junior</al:Puesto>
                <al:HorasTrabajadas>300</al:HorasTrabajadas>
            </al:ExperienciaProfesional>
            <al:ExperienciaProfesional>
                <al:NombreEmpresa>PSI Software AG</al:NombreEmpresa>
                <al:Puesto>Programador Junior</al:Puesto>
                <al:HorasTrabajadas>279</al:HorasTrabajadas>
            </al:ExperienciaProfesional>
        </al:ExperienciasProfesionales>
    </Estudiante>



</Erasmus>

=== Carlosdi1106/visualizadorCurricula/visualizadorCurricula/input/victorGarcia.xml
<?xml version="1.0" encoding="UTF-8"?>
<era:Erasmus xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:es="http://www.erasmus-espana.org" 
    xmlns:era="http://www.erasmus.org"
    xs:schemaLocation="http://www.erasmus-espana.org espana.xsd 
    http://www.erasmus.org erasmus.xsd"> 
     
    <era:Estudiante NumeroIdentificacion="1112223334A" xs:type="es:estudianteEspanaT">
        <era:NombreCompleto>
            <era:Nombre>Victor</era:Nombre>
            <era:PrimerApellido>Garcia</era:PrimerApellido>
            <era:SegundoApellido>Perez</era:SegundoApellido>
        </era:NombreCompleto>
        <era:FechaNacimiento>2002-02-27</era:FechaNacimiento>
        <era:Universidad xs:type="es:universidadEspanaT">
            <era:NombreUni>UPV/EHU</era:NombreUni>
            <era:Procedencia xs:type="es:procedenciaEspanaT">
                <era:Pais>Espana</era:Pais>  
                <era:CodigoPostal>20001</era:CodigoPostal>
                <era:Ciudad>Donosti</era:Ciudad>
                <es:ComunidadAutonoma>Pais Vasco</es:ComunidadAutonoma>
                <es:Provincia>Gipuzkoa</es:Provincia>
                <es:PersonaDeContacto>
                    <era:PrefijoTelefono>34</era:PrefijoTelefono>
                    <era:Telefono>111222111</era:Telefono>
                    <era:CorreoElectronico>persona@contacto.es</era:CorreoElectronico>
                    <era:Direccion>
                        <era:Pais>Espana</era:Pais>
                        <era:CodigoPostal>01002</era:CodigoPostal>
                        <era:Ciudad>Vitora</era:Ciudad>
                        <era:NombreCalle>Portal de Castilla</era:NombreCalle>
                        <era:NumeroPortal>1</era:NumeroPortal>
                        <era:Piso>1</era:Piso>
                        <era:Puerta>Derecha</era:Puerta>
                    </era:Direccion>
                </es:PersonaDeContacto>
            </era:Procedencia> 
            <era:Grados Curso="3" xs:type="es:gradoEspanaT">
                <era:Grado>Ingenieria Informatica</era:Grado>
                <era:Facultad>Informatica</era:Facultad>
                <era:Campus>Gipuzkoa</era:Campus>
            </era:Grados>
            <es:Coordinador>
                <es:Nombre>Borja</es:Nombre>
                <es:Apellido>Calvo</es:Apellido>
                <es:Email>informatica.internacional@ikasle.ehu.es</es:Email>
                <es:Telefono>111222333</es:Telefono>
            </es:Coordinador>
        </era:Universidad>
        <era:DatosContacto>
            <era:PrefijoTelefono>34</era:PrefijoTelefono>
            <era:Telefono>111222333</era:Telefono>
            <era:CorreoElectronico>victor@garcia.com</era:CorreoElectronico>
            <era:Direccion>
                <era:Pais>Espana</era:Pais>
                <era:CodigoPostal>01010</era:CodigoPostal>
                <era:Ciudad>Vitoria</era:Ciudad>
                <era:NombreCalle>Portal de Castilla</era:NombreCalle>
                <era:NumeroPortal>1</era:NumeroPortal>
                <era:Piso>1ero</era:Piso>
                <era:Puerta>Derecha</era:Puerta>
            </era:Direccion>
        </era:DatosContacto>
        <era:CartaPresentacion>
            I'm so pleased i can go to <era:UniversidadDestino>Tartu University</era:UniversidadDestino>
            in the beautiful country of <era:PaisDestino>Estonia</era:PaisDestino>. 
            Can't wait for the day i assist to your classes
        </era:CartaPresentacion>
        <era:NivelIdiomas>
            <era:Certificado Idioma="Ingles">C1</era:Certificado>
            <era:Certificado Idioma="Euskera">B2</era:Certificado>
        </era:NivelIdiomas>
        <era:Asignaturas>
            <era:Asignatura NombreAsignatura="DBD">
                <era:Cuatrimestre>Segundo</era:Cuatrimestre>
                <era:Creditos>12</era:Creditos>
            </era:Asignatura>
            <era:Asignatura NombreAsignatura="MD">
                <era:Cuatrimestre>Anual</era:Cuatrimestre>
                <era:Creditos>12</era:Creditos>
            </era:Asignatura>
            <era:Asignatura NombreAsignatura="LCSI">
                <era:Cuatrimestre>Segundo</era:Cuatrimestre>
                <era:Creditos>12</era:Creditos>
            </era:Asignatura>
            <era:Asignatura NombreAsignatura="IO">
                <era:Cuatrimestre>Primero</era:Cuatrimestre>
                <era:Creditos>12</era:Creditos>
            </era:Asignatura>
        </era:Asignaturas>
        <era:CuatrimestreDeEstancia>Anual</era:CuatrimestreDeEstancia>
        <es:Beca TipoBeca="Privada">
            <es:NombreBeca>BBVA becas erasmus Locuras</es:NombreBeca>
            <es:InstitucionEmisora>BBVA</es:InstitucionEmisora>
            <es:Importe>700</es:Importe>
        </es:Beca>
        <es:Beca TipoBeca="Estatal">
            <es:NombreBeca>Gobierno vasco internacionalizacion</es:NombreBeca>
            <es:InstitucionEmisora>Gobierno Vasco</es:InstitucionEmisora>
            <es:Importe>700</es:Importe>
        </es:Beca>
    </era:Estudiante>
</era:Erasmus>
